### ISSUE TITLE
How to use Steppers without Encoders?

### ISSUE THREAD

**Issue by TehseenHasan** [FarmBot/farmbot-arduino-firmware#162]
I am developing this FarmBot and currently, I am buying the hardware parts. I will use **Arduino Mega + RAMPS Shield + DRV8825, Drivers,** instead of the Farmduino board, so any suggestion to use this Arduino+RAMPS combination??? 
I also want to know that **can I skip the encoders** and use the steppers in the open-loop mode. Would the FarmBot work without encoders?

**Comment by RickCarlino** [comment]
@TehseenHasan Yes, this is possible. You would need to disable encoders in the device settings page shown below:
![image](https://user-images.githubusercontent.com/1388608/130367965-c389a548-2273-45c8-b905-e1644fb0b30e.png)

 A few things to note:

1. Without encoders, you will need to manually SET ZERO every time you power the device on.
2. FarmBot technically supports the use of end-stops to detect the HOME position (you will need to enable ADVANCED SETTINGS). The issue with end stops is FarmBot has never actually sold a kit that uses end stops. Because of this we don't know how well end stops work (no one at FarmBot has tested the reliability of end stops in recent years). It might work, but I do want to warn you that supporting end stops is not a high priority for us as a company (our main focus is supporting users of official FarmBot kits). That's not to say end stops don't work. It's just that they are not officially supported in the way that encoders are.

Does that help? Please let me know if you have any other issues. I will close the issue for now but am happy to answer any other questions you have.
