### ISSUE TITLE
NTH? Support for one more axis? A?

### ISSUE THREAD

**Issue by burk80** [FarmBot/farmbot-arduino-firmware#164]
In the cnc world there is support to make an extra axis ..

To make a rotary tool in a flat bed cnc for example.. 

Would it be possible to add an extra axis to make it possible to travel between beds in the future?

Im thinking a carrige or similar that moves the gountry to another bed.. 

Regards 
Marcus

**Comment by roryaronson** [comment]
While this is possible (and most of the FarmBot electronics boards already have an extra stepper motor output), we are very resource constrained and have no plans to add such a feature anytime soon to our firmware and the other parts of the software stack. That being said, PRs are always welcome!

Alternatively, you could use external CNC electronics and an external control system that orchestrates commands between the extra motors and the FarmBot using FarmBot-Py, our API, FarmBotJS, etc. See more info on our [developer docs](https://developer.farm.bot/). I would recommend this approach because if your goal is to move the entire FarmBot you are likely going to need more power and more than one motor than what the stock electronics support. It will also be the cleanest way to implement such an idea because it would not require any changes to the main FarmBot software.
